### ISSUE TITLE
Implementing a rover

### ISSUE THREAD

**Issue by linuxsocke** [Intelligent-Quads/iq_sim#3]
Hello, 
I tried to implement a rover. So far if followed the husky implementation in [swiftgust](https://github.com/SwiftGust/ardupilot_gazebo)'s repo but I was missing the libhusky_gazebo_plugin.so for the skid drive controller. So I substituted it with libgazebo_ros_skid_steer_drive.so.

I launched mavproxy with the following args:

`sim_vehicle.py -v APMrover2 -f gazebo-rover --map -I 0`

My mavproxy connection works and it is also arming but when assigning a go to goal command it wont drive.

Which differential drive plugin works with ardupilot?

**Comment by ericjohnson97** [comment]
I remember that I was able to get swifgust's rover to work. Thats what I used as the base for the boat. Since a boat in ardupilot is a rover with propellers XD.  The issue I had with switgust's rover implementation was that the wheels had way to much traction, so then the rover wasn't able to turn. by lowering the wheel friction coefficients I was able to get the rover to work just fine.

**Comment by linuxsocke** [comment]
Ok, thanks. I though there should be rover implementation because I found a gazebo-rover.parm in the ardupilot code base.
